# Generated by Django 5.2.6 on 2025-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='content',
            field=models.TextField(default='dasd'),
            preserve_default=False,
        ),
    ]
